[package]
name = "awc_examples"
version = "0.1.0"
authors = ["zhangboyu <zhangboyu@gmail.com>"]

[dependencies]
actix = "0.7"
actix-web = { version="0.7.3", features=["rust-tls"] }

futures = "0.1"
serde = "1.0.43"
serde_derive = "1.0.43"
serde_json = "1.0.16"
validator = "0.6.3"
validator_derive = "0.6.5"
env_logger = "0.5.9"
