[package]
name = "multipart-example"
version = "0.1.0"
authors = ["juniper <juniper@gmail.com>"]

[[bin]]
name = "multipart"
path = "src/main.rs"

[dependencies]
env_logger = "*"
futures = "0.1"

actix = "0.7"
actix-web = "0.7"
