[package]
name = "protobuf-example"
version = "0.1.0"
authors = ["zhangboyu <zhangboyu@126.com>"]


[dependencies]
bytes = "0.4"
futures = "0.1"
failure = "0.1"
env_logger = "*"

prost = "0.2.0"
prost-derive = "0.2.0"

actix = "0.7"
actix-web = "0.7"
