[package]
name = "redis-session"
version = "0.1.0"
authors = ["zhangboyu <zhangboyu@gmail.com>"]

[dependencies]
env_logger = "0.5"
actix = "0.7"
actix-web = "0.7.3"
actix-redis = { version = "0.5.1", features = ["web"] }
