[package]
name = "cookie-session"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
workspace = "../"

[dependencies]
actix = "0.7"
actix-web = "^0.7"

futures = "0.1"
time = "0.1"
env_logger = "0.5"
