[package]
name = "tokio-echo"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
bytes = { git = "https://github.com/carllerche/bytes" }
futures = "0.1"
tokio-core = "0.1"
tokio-proto = { git = "https://github.com/tokio-rs/tokio-proto" }
