[package]
name = "cookie-auth-full"
version = "0.1.0"
authors = ["zhangboyu <zhangboyu@gmail.com>"]


[dependencies]
actix = "0.7"
actix-web = "0.7"

cookie = { version="0.11", features=["percent-encode", "secure"] }
futures = "0.1"
time = "0.1"
env_logger = "0.5"
