[package]
name = "template-askama"
version = "0.1.0"
authors = ["zhangjunfang <zhangjunfang@gmail.com>"]

[dependencies]
env_logger = "0.5"
askama = "0.6"

actix = "0.7"
actix-web = "0.7"

[build-dependencies]
askama = "0.6"
